export const NIFTY_STOCKS = [
  "ADANIENT.NS","ADANIPORTS.NS","APOLLOHOSP.NS","ASIANPAINT.NS","AXISBANK.NS",
  "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BEL.NS","BHARTIARTL.NS",
  "CIPLA.NS","COALINDIA.NS","DRREDDY.NS","EICHERMOT.NS","ETERNAL.NS",
  "GRASIM.NS","HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS","HINDALCO.NS",
  "HINDUNILVR.NS","ICICIBANK.NS","ITC.NS","INFY.NS","INDIGO.NS",
  "JSWSTEEL.NS","JIOFIN.NS","KOTAKBANK.NS","LT.NS","M&M.NS",
  "MARUTI.NS","MAXHEALTH.NS","NTPC.NS","NESTLEIND.NS","ONGC.NS",
  "POWERGRID.NS","RELIANCE.NS","SBILIFE.NS","SHRIRAMFIN.NS","SBIN.NS",
  "SUNPHARMA.NS","TCS.NS","TATACONSUM.NS","TMPV.NS","TATASTEEL.NS",
  "TECHM.NS","TITAN.NS","TRENT.NS","ULTRACEMCO.NS","WIPRO.NS",
] as const;

export const BANKNIFTY_STOCKS = [
  "HDFCBANK.NS","ICICIBANK.NS","KOTAKBANK.NS","AXISBANK.NS","SBIN.NS",
  "INDUSINDBK.NS","AUBANK.NS","FEDERALBNK.NS","IDFCFIRSTB.NS","BANDHANBNK.NS",
  "PNB.NS","BANKBARODA.NS",
] as const;

export const SENSEX_STOCKS = [
  "ADANIPORTS.NS","ASIANPAINT.NS","AXISBANK.NS","BAJFINANCE.NS","BAJAJFINSV.NS",
  "BEL.NS","BHARTIARTL.NS","ETERNAL.NS","HCLTECH.NS","HDFCBANK.NS",
  "HINDUNILVR.NS","ICICIBANK.NS","INFY.NS","INDIGO.NS","ITC.NS",
  "KOTAKBANK.NS","LT.NS","M&M.NS","MARUTI.NS","NTPC.NS",
  "POWERGRID.NS","RELIANCE.NS","SBIN.NS","SUNPHARMA.NS","TCS.NS",
  "TATASTEEL.NS","TECHM.NS","TITAN.NS","TRENT.NS","ULTRACEMCO.NS",
] as const;
