/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SensexRouteImport } from './routes/sensex'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as OptionchainRouteImport } from './routes/optionchain'
import { Route as OiAnalysisProRouteImport } from './routes/oi-analysis-pro'
import { Route as OiAnalysisRouteImport } from './routes/oi-analysis'
import { Route as Nifty50RouteImport } from './routes/nifty50'
import { Route as IndexContributionRouteImport } from './routes/index-contribution'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FutureDashboardRouteImport } from './routes/future-dashboard'
import { Route as FnoboardRouteImport } from './routes/fnoboard'
import { Route as FnoRouteImport } from './routes/fno'
import { Route as BankniftyRouteImport } from './routes/banknifty'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorKeyRouteImport } from './routes/sector.$key'
import { Route as ApiOptionHistoryRouteImport } from './routes/api/option-history'
import { Route as ApiOiHistoryRouteImport } from './routes/api/oi-history'
import { Route as ApiMarketHistoryRouteImport } from './routes/api/market-history'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiBreadthHistoryRouteImport } from './routes/api/breadth-history'
import { Route as ApiHistorySymbolRouteImport } from './routes/api/history.$symbol'
import { Route as ApiCandlesSymbolRouteImport } from './routes/api/candles.$symbol'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SensexRoute = SensexRouteImport.update({
  id: '/sensex',
  path: '/sensex',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionchainRoute = OptionchainRouteImport.update({
  id: '/optionchain',
  path: '/optionchain',
  getParentRoute: () => rootRouteImport,
} as any)
const OiAnalysisProRoute = OiAnalysisProRouteImport.update({
  id: '/oi-analysis-pro',
  path: '/oi-analysis-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const OiAnalysisRoute = OiAnalysisRouteImport.update({
  id: '/oi-analysis',
  path: '/oi-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const Nifty50Route = Nifty50RouteImport.update({
  id: '/nifty50',
  path: '/nifty50',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexContributionRoute = IndexContributionRouteImport.update({
  id: '/index-contribution',
  path: '/index-contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureDashboardRoute = FutureDashboardRouteImport.update({
  id: '/future-dashboard',
  path: '/future-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FnoboardRoute = FnoboardRouteImport.update({
  id: '/fnoboard',
  path: '/fnoboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FnoRoute = FnoRouteImport.update({
  id: '/fno',
  path: '/fno',
  getParentRoute: () => rootRouteImport,
} as any)
const BankniftyRoute = BankniftyRouteImport.update({
  id: '/banknifty',
  path: '/banknifty',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorKeyRoute = SectorKeyRouteImport.update({
  id: '/sector/$key',
  path: '/sector/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOptionHistoryRoute = ApiOptionHistoryRouteImport.update({
  id: '/api/option-history',
  path: '/api/option-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOiHistoryRoute = ApiOiHistoryRouteImport.update({
  id: '/api/oi-history',
  path: '/api/oi-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketHistoryRoute = ApiMarketHistoryRouteImport.update({
  id: '/api/market-history',
  path: '/api/market-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBreadthHistoryRoute = ApiBreadthHistoryRouteImport.update({
  id: '/api/breadth-history',
  path: '/api/breadth-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistorySymbolRoute = ApiHistorySymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => ApiHistoryRoute,
} as any)
const ApiCandlesSymbolRoute = ApiCandlesSymbolRouteImport.update({
  id: '/api/candles/$symbol',
  path: '/api/candles/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/future-dashboard': typeof FutureDashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/index-contribution': typeof IndexContributionRoute
  '/nifty50': typeof Nifty50Route
  '/oi-analysis': typeof OiAnalysisRoute
  '/oi-analysis-pro': typeof OiAnalysisProRoute
  '/optionchain': typeof OptionchainRoute
  '/screener': typeof ScreenerRoute
  '/sensex': typeof SensexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/breadth-history': typeof ApiBreadthHistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/market-history': typeof ApiMarketHistoryRoute
  '/api/oi-history': typeof ApiOiHistoryRoute
  '/api/option-history': typeof ApiOptionHistoryRoute
  '/sector/$key': typeof SectorKeyRoute
  '/api/candles/$symbol': typeof ApiCandlesSymbolRoute
  '/api/history/$symbol': typeof ApiHistorySymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/future-dashboard': typeof FutureDashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/index-contribution': typeof IndexContributionRoute
  '/nifty50': typeof Nifty50Route
  '/oi-analysis': typeof OiAnalysisRoute
  '/oi-analysis-pro': typeof OiAnalysisProRoute
  '/optionchain': typeof OptionchainRoute
  '/screener': typeof ScreenerRoute
  '/sensex': typeof SensexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/breadth-history': typeof ApiBreadthHistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/market-history': typeof ApiMarketHistoryRoute
  '/api/oi-history': typeof ApiOiHistoryRoute
  '/api/option-history': typeof ApiOptionHistoryRoute
  '/sector/$key': typeof SectorKeyRoute
  '/api/candles/$symbol': typeof ApiCandlesSymbolRoute
  '/api/history/$symbol': typeof ApiHistorySymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/future-dashboard': typeof FutureDashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/index-contribution': typeof IndexContributionRoute
  '/nifty50': typeof Nifty50Route
  '/oi-analysis': typeof OiAnalysisRoute
  '/oi-analysis-pro': typeof OiAnalysisProRoute
  '/optionchain': typeof OptionchainRoute
  '/screener': typeof ScreenerRoute
  '/sensex': typeof SensexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/breadth-history': typeof ApiBreadthHistoryRoute
  '/api/export': typeof ApiExportRoute
  '/api/history': typeof ApiHistoryRouteWithChildren
  '/api/market-history': typeof ApiMarketHistoryRoute
  '/api/oi-history': typeof ApiOiHistoryRoute
  '/api/option-history': typeof ApiOptionHistoryRoute
  '/sector/$key': typeof SectorKeyRoute
  '/api/candles/$symbol': typeof ApiCandlesSymbolRoute
  '/api/history/$symbol': typeof ApiHistorySymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/future-dashboard'
    | '/heatmap'
    | '/index-contribution'
    | '/nifty50'
    | '/oi-analysis'
    | '/oi-analysis-pro'
    | '/optionchain'
    | '/screener'
    | '/sensex'
    | '/sitemap.xml'
    | '/api/breadth-history'
    | '/api/export'
    | '/api/history'
    | '/api/market-history'
    | '/api/oi-history'
    | '/api/option-history'
    | '/sector/$key'
    | '/api/candles/$symbol'
    | '/api/history/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/future-dashboard'
    | '/heatmap'
    | '/index-contribution'
    | '/nifty50'
    | '/oi-analysis'
    | '/oi-analysis-pro'
    | '/optionchain'
    | '/screener'
    | '/sensex'
    | '/sitemap.xml'
    | '/api/breadth-history'
    | '/api/export'
    | '/api/history'
    | '/api/market-history'
    | '/api/oi-history'
    | '/api/option-history'
    | '/sector/$key'
    | '/api/candles/$symbol'
    | '/api/history/$symbol'
  id:
    | '__root__'
    | '/'
    | '/ai-analysis'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/future-dashboard'
    | '/heatmap'
    | '/index-contribution'
    | '/nifty50'
    | '/oi-analysis'
    | '/oi-analysis-pro'
    | '/optionchain'
    | '/screener'
    | '/sensex'
    | '/sitemap.xml'
    | '/api/breadth-history'
    | '/api/export'
    | '/api/history'
    | '/api/market-history'
    | '/api/oi-history'
    | '/api/option-history'
    | '/sector/$key'
    | '/api/candles/$symbol'
    | '/api/history/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  BankniftyRoute: typeof BankniftyRoute
  FnoRoute: typeof FnoRoute
  FnoboardRoute: typeof FnoboardRoute
  FutureDashboardRoute: typeof FutureDashboardRoute
  HeatmapRoute: typeof HeatmapRoute
  IndexContributionRoute: typeof IndexContributionRoute
  Nifty50Route: typeof Nifty50Route
  OiAnalysisRoute: typeof OiAnalysisRoute
  OiAnalysisProRoute: typeof OiAnalysisProRoute
  OptionchainRoute: typeof OptionchainRoute
  ScreenerRoute: typeof ScreenerRoute
  SensexRoute: typeof SensexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiBreadthHistoryRoute: typeof ApiBreadthHistoryRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiHistoryRoute: typeof ApiHistoryRouteWithChildren
  ApiMarketHistoryRoute: typeof ApiMarketHistoryRoute
  ApiOiHistoryRoute: typeof ApiOiHistoryRoute
  ApiOptionHistoryRoute: typeof ApiOptionHistoryRoute
  SectorKeyRoute: typeof SectorKeyRoute
  ApiCandlesSymbolRoute: typeof ApiCandlesSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensex': {
      id: '/sensex'
      path: '/sensex'
      fullPath: '/sensex'
      preLoaderRoute: typeof SensexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optionchain': {
      id: '/optionchain'
      path: '/optionchain'
      fullPath: '/optionchain'
      preLoaderRoute: typeof OptionchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oi-analysis-pro': {
      id: '/oi-analysis-pro'
      path: '/oi-analysis-pro'
      fullPath: '/oi-analysis-pro'
      preLoaderRoute: typeof OiAnalysisProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oi-analysis': {
      id: '/oi-analysis'
      path: '/oi-analysis'
      fullPath: '/oi-analysis'
      preLoaderRoute: typeof OiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nifty50': {
      id: '/nifty50'
      path: '/nifty50'
      fullPath: '/nifty50'
      preLoaderRoute: typeof Nifty50RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index-contribution': {
      id: '/index-contribution'
      path: '/index-contribution'
      fullPath: '/index-contribution'
      preLoaderRoute: typeof IndexContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-dashboard': {
      id: '/future-dashboard'
      path: '/future-dashboard'
      fullPath: '/future-dashboard'
      preLoaderRoute: typeof FutureDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fnoboard': {
      id: '/fnoboard'
      path: '/fnoboard'
      fullPath: '/fnoboard'
      preLoaderRoute: typeof FnoboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fno': {
      id: '/fno'
      path: '/fno'
      fullPath: '/fno'
      preLoaderRoute: typeof FnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banknifty': {
      id: '/banknifty'
      path: '/banknifty'
      fullPath: '/banknifty'
      preLoaderRoute: typeof BankniftyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$key': {
      id: '/sector/$key'
      path: '/sector/$key'
      fullPath: '/sector/$key'
      preLoaderRoute: typeof SectorKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/option-history': {
      id: '/api/option-history'
      path: '/api/option-history'
      fullPath: '/api/option-history'
      preLoaderRoute: typeof ApiOptionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oi-history': {
      id: '/api/oi-history'
      path: '/api/oi-history'
      fullPath: '/api/oi-history'
      preLoaderRoute: typeof ApiOiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-history': {
      id: '/api/market-history'
      path: '/api/market-history'
      fullPath: '/api/market-history'
      preLoaderRoute: typeof ApiMarketHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/breadth-history': {
      id: '/api/breadth-history'
      path: '/api/breadth-history'
      fullPath: '/api/breadth-history'
      preLoaderRoute: typeof ApiBreadthHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$symbol': {
      id: '/api/history/$symbol'
      path: '/$symbol'
      fullPath: '/api/history/$symbol'
      preLoaderRoute: typeof ApiHistorySymbolRouteImport
      parentRoute: typeof ApiHistoryRoute
    }
    '/api/candles/$symbol': {
      id: '/api/candles/$symbol'
      path: '/api/candles/$symbol'
      fullPath: '/api/candles/$symbol'
      preLoaderRoute: typeof ApiCandlesSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiHistoryRouteChildren {
  ApiHistorySymbolRoute: typeof ApiHistorySymbolRoute
}

const ApiHistoryRouteChildren: ApiHistoryRouteChildren = {
  ApiHistorySymbolRoute: ApiHistorySymbolRoute,
}

const ApiHistoryRouteWithChildren = ApiHistoryRoute._addFileChildren(
  ApiHistoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  BankniftyRoute: BankniftyRoute,
  FnoRoute: FnoRoute,
  FnoboardRoute: FnoboardRoute,
  FutureDashboardRoute: FutureDashboardRoute,
  HeatmapRoute: HeatmapRoute,
  IndexContributionRoute: IndexContributionRoute,
  Nifty50Route: Nifty50Route,
  OiAnalysisRoute: OiAnalysisRoute,
  OiAnalysisProRoute: OiAnalysisProRoute,
  OptionchainRoute: OptionchainRoute,
  ScreenerRoute: ScreenerRoute,
  SensexRoute: SensexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBreadthHistoryRoute: ApiBreadthHistoryRoute,
  ApiExportRoute: ApiExportRoute,
  ApiHistoryRoute: ApiHistoryRouteWithChildren,
  ApiMarketHistoryRoute: ApiMarketHistoryRoute,
  ApiOiHistoryRoute: ApiOiHistoryRoute,
  ApiOptionHistoryRoute: ApiOptionHistoryRoute,
  SectorKeyRoute: SectorKeyRoute,
  ApiCandlesSymbolRoute: ApiCandlesSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
