/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SensexRouteImport } from './routes/sensex'
import { Route as OptionchainRouteImport } from './routes/optionchain'
import { Route as Nifty50RouteImport } from './routes/nifty50'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as FnoboardRouteImport } from './routes/fnoboard'
import { Route as FnoRouteImport } from './routes/fno'
import { Route as BankniftyRouteImport } from './routes/banknifty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorKeyRouteImport } from './routes/sector.$key'

const SensexRoute = SensexRouteImport.update({
  id: '/sensex',
  path: '/sensex',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionchainRoute = OptionchainRouteImport.update({
  id: '/optionchain',
  path: '/optionchain',
  getParentRoute: () => rootRouteImport,
} as any)
const Nifty50Route = Nifty50RouteImport.update({
  id: '/nifty50',
  path: '/nifty50',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FnoboardRoute = FnoboardRouteImport.update({
  id: '/fnoboard',
  path: '/fnoboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FnoRoute = FnoRouteImport.update({
  id: '/fno',
  path: '/fno',
  getParentRoute: () => rootRouteImport,
} as any)
const BankniftyRoute = BankniftyRouteImport.update({
  id: '/banknifty',
  path: '/banknifty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorKeyRoute = SectorKeyRouteImport.update({
  id: '/sector/$key',
  path: '/sector/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/heatmap': typeof HeatmapRoute
  '/nifty50': typeof Nifty50Route
  '/optionchain': typeof OptionchainRoute
  '/sensex': typeof SensexRoute
  '/sector/$key': typeof SectorKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/heatmap': typeof HeatmapRoute
  '/nifty50': typeof Nifty50Route
  '/optionchain': typeof OptionchainRoute
  '/sensex': typeof SensexRoute
  '/sector/$key': typeof SectorKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banknifty': typeof BankniftyRoute
  '/fno': typeof FnoRoute
  '/fnoboard': typeof FnoboardRoute
  '/heatmap': typeof HeatmapRoute
  '/nifty50': typeof Nifty50Route
  '/optionchain': typeof OptionchainRoute
  '/sensex': typeof SensexRoute
  '/sector/$key': typeof SectorKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/heatmap'
    | '/nifty50'
    | '/optionchain'
    | '/sensex'
    | '/sector/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/heatmap'
    | '/nifty50'
    | '/optionchain'
    | '/sensex'
    | '/sector/$key'
  id:
    | '__root__'
    | '/'
    | '/banknifty'
    | '/fno'
    | '/fnoboard'
    | '/heatmap'
    | '/nifty50'
    | '/optionchain'
    | '/sensex'
    | '/sector/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankniftyRoute: typeof BankniftyRoute
  FnoRoute: typeof FnoRoute
  FnoboardRoute: typeof FnoboardRoute
  HeatmapRoute: typeof HeatmapRoute
  Nifty50Route: typeof Nifty50Route
  OptionchainRoute: typeof OptionchainRoute
  SensexRoute: typeof SensexRoute
  SectorKeyRoute: typeof SectorKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sensex': {
      id: '/sensex'
      path: '/sensex'
      fullPath: '/sensex'
      preLoaderRoute: typeof SensexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optionchain': {
      id: '/optionchain'
      path: '/optionchain'
      fullPath: '/optionchain'
      preLoaderRoute: typeof OptionchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nifty50': {
      id: '/nifty50'
      path: '/nifty50'
      fullPath: '/nifty50'
      preLoaderRoute: typeof Nifty50RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fnoboard': {
      id: '/fnoboard'
      path: '/fnoboard'
      fullPath: '/fnoboard'
      preLoaderRoute: typeof FnoboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fno': {
      id: '/fno'
      path: '/fno'
      fullPath: '/fno'
      preLoaderRoute: typeof FnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banknifty': {
      id: '/banknifty'
      path: '/banknifty'
      fullPath: '/banknifty'
      preLoaderRoute: typeof BankniftyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector/$key': {
      id: '/sector/$key'
      path: '/sector/$key'
      fullPath: '/sector/$key'
      preLoaderRoute: typeof SectorKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankniftyRoute: BankniftyRoute,
  FnoRoute: FnoRoute,
  FnoboardRoute: FnoboardRoute,
  HeatmapRoute: HeatmapRoute,
  Nifty50Route: Nifty50Route,
  OptionchainRoute: OptionchainRoute,
  SensexRoute: SensexRoute,
  SectorKeyRoute: SectorKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
